name: 'Módulo III - Laboratorios Móviles CI/CD'

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'server/routes/lab.js'
      - 'server/database/lab-*.sql'
      - 'server/utils/lab-*.js'
      - 'server/scripts/load-lab-seed-data.js'
      - 'server/__tests__/lab.test.js'
      - 'client/src/app/**/lab/**'
      - 'client/src/components/lab/**'
      - 'tests/e2e/lab-*.spec.js'
      - '.github/workflows/lab-module-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'server/routes/lab.js'
      - 'server/database/lab-*.sql'
      - 'server/utils/lab-*.js'
      - 'server/scripts/load-lab-seed-data.js'
      - 'server/__tests__/lab.test.js'
      - 'client/src/app/**/lab/**'
      - 'client/src/components/lab/**'
      - 'tests/e2e/lab-*.spec.js'

env:
  NODE_VERSION: '18'
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  # ====================================================================
  # JOB 1: LINT Y VALIDACIÓN DE CÓDIGO
  # ====================================================================
  lint-lab-module:
    name: '🔍 Lint Módulo Laboratorios'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      
      - name: Instalar dependencias del servidor
        run: |
          cd server
          npm ci
      
      - name: Instalar dependencias del cliente
        run: |
          cd client
          npm ci
      
      - name: Lint archivos del módulo de laboratorios (Backend)
        run: |
          cd server
          npx eslint routes/lab.js utils/lab-*.js --format=github
      
      - name: Lint archivos del módulo de laboratorios (Frontend)
        run: |
          cd client
          npx eslint src/app/**/lab/** src/components/lab/** --ext .tsx,.ts --format=github

  # ====================================================================
  # JOB 2: TESTS UNITARIOS DEL MÓDULO
  # ====================================================================
  unit-tests-lab:
    name: '🧪 Tests Unitarios - Laboratorios'
    runs-on: ubuntu-latest
    needs: lint-lab-module
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'
      
      - name: Instalar dependencias
        run: |
          cd server
          npm ci
      
      - name: Ejecutar tests unitarios del módulo
        run: |
          cd server
          npm run test:lab
        env:
          NODE_ENV: test
      
      - name: Subir coverage del módulo
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: lab-module
          name: lab-module-coverage
          fail_ci_if_error: false

  # ====================================================================
  # JOB 3: VALIDACIÓN DE ESQUEMA DE BASE DE DATOS
  # ====================================================================
  validate-lab-schema:
    name: '🗄️ Validar Esquema BD - Laboratorios'
    runs-on: ubuntu-latest
    needs: lint-lab-module
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: edu21_lab_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'server/package-lock.json'
      
      - name: Instalar dependencias
        run: |
          cd server
          npm ci
      
      - name: Validar esquema de laboratorios
        run: |
          cd server
          # Simular aplicación del esquema
          echo "Validando esquema lab-schema.sql..."
          node -e "
            const fs = require('fs');
            const schema = fs.readFileSync('database/lab-schema.sql', 'utf8');
            if (!schema.includes('lab_product') || !schema.includes('lab_activity')) {
              throw new Error('Esquema incompleto');
            }
            console.log('✅ Esquema válido');
          "
      
      - name: Validar datos semilla
        run: |
          cd server
          node -e "
            const seedData = require('./database/lab-seed-data.json');
            if (seedData.products.length !== 10 || seedData.activities.length !== 40) {
              throw new Error('Datos semilla incompletos');
            }
            console.log('✅ Datos semilla válidos');
          "

  # ====================================================================
  # JOB 4: TESTS E2E DEL MÓDULO
  # ====================================================================
  e2e-tests-lab:
    name: '🎭 Tests E2E - Laboratorios'
    runs-on: ubuntu-latest
    needs: [unit-tests-lab, validate-lab-schema]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      
      - name: Instalar dependencias del servidor
        run: |
          cd server
          npm ci
      
      - name: Instalar dependencias del cliente
        run: |
          cd client
          npm ci
      
      - name: Instalar Playwright
        run: npx playwright install --with-deps
      
      - name: Iniciar servidor de desarrollo
        run: |
          cd server
          npm start &
          sleep 10
        env:
          NODE_ENV: development
          PORT: 5000
      
      - name: Iniciar cliente de desarrollo
        run: |
          cd client
          npm run dev &
          sleep 15
        env:
          NODE_ENV: development
          NEXT_PUBLIC_API_URL: http://localhost:5000
      
      - name: Esperar servicios disponibles
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
          timeout 60 bash -c 'until curl -f http://localhost:5000/api/health; do sleep 2; done'
      
      - name: Ejecutar tests E2E del módulo de laboratorios
        run: npx playwright test tests/e2e/lab-*.spec.js
        env:
          CI: true
      
      - name: Subir artifacts de Playwright
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: lab-playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 7

  # ====================================================================
  # JOB 5: BUILD Y VALIDACIÓN DE INTEGRACIÓN
  # ====================================================================
  build-integration-test:
    name: '🏗️ Build & Test Integración'
    runs-on: ubuntu-latest
    needs: [unit-tests-lab, validate-lab-schema]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      
      - name: Instalar dependencias
        run: |
          cd server && npm ci
          cd ../client && npm ci
      
      - name: Build del cliente (validar que el módulo compila)
        run: |
          cd client
          npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: http://localhost:5000
      
      - name: Verificar rutas del módulo en build
        run: |
          cd client
          # Verificar que las páginas del módulo se generaron
          test -d ".next/server/app/teacher/lab" || echo "⚠️ Páginas del módulo no encontradas"
          echo "✅ Build completado con módulo de laboratorios"
      
      - name: Test de integración con plataforma existente
        run: |
          cd server
          # Test que verifica que el módulo no rompe la plataforma existente
          node -e "
            const express = require('express');
            const labRoutes = require('./routes/lab.js');
            const app = express();
            app.use('/api/lab', labRoutes);
            console.log('✅ Módulo de laboratorios se integra correctamente');
          "

  # ====================================================================
  # JOB 6: SECURITY SCAN ESPECÍFICO DEL MÓDULO
  # ====================================================================
  security-scan-lab:
    name: '🔒 Security Scan - Laboratorios'
    runs-on: ubuntu-latest
    needs: lint-lab-module
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Ejecutar audit de NPM en dependencias del módulo
        run: |
          cd server
          npm audit --audit-level moderate
      
      - name: Scan de código con CodeQL (solo archivos del módulo)
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          queries: security-and-quality
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      
      - name: Ejecutar análisis CodeQL
        uses: github/codeql-action/analyze@v2

  # ====================================================================
  # JOB 7: DEPLOYMENT PREVIEW (SOLO EN PR)
  # ====================================================================
  deploy-preview:
    name: '🚀 Deploy Preview'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [e2e-tests-lab, build-integration-test, security-scan-lab]
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Deploy a Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./client
          scope: ${{ secrets.VERCEL_ORG_ID }}
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.PREVIEW_API_URL }}

  # ====================================================================
  # JOB 8: PRODUCTION DEPLOYMENT (SOLO EN MAIN)
  # ====================================================================
  deploy-production:
    name: '🎯 Deploy Producción'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [e2e-tests-lab, build-integration-test, security-scan-lab]
    environment: production
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - name: Deploy a Vercel Production
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./client
          scope: ${{ secrets.VERCEL_ORG_ID }}
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.PRODUCTION_API_URL }}
      
      - name: Cargar datos semilla en producción
        run: |
          cd server
          npm ci
          node scripts/load-lab-seed-data.js
        env:
          NODE_ENV: production
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      - name: Notificar deployment exitoso
        uses: 8398a7/action-slack@v3
        with:
          status: success
          text: '🎉 Módulo III - Laboratorios Móviles desplegado exitosamente en producción!'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # ====================================================================
  # JOB 9: VALIDACIÓN POST-DEPLOYMENT
  # ====================================================================
  post-deployment-validation:
    name: '✅ Validación Post-Deploy'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: deploy-production
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Instalar dependencias de testing
        run: |
          npm install -g @playwright/test
          npx playwright install
      
      - name: Tests de smoke en producción
        run: |
          npx playwright test tests/e2e/lab-smoke.spec.js
        env:
          BASE_URL: ${{ secrets.PRODUCTION_URL }}
          CI: true
      
      - name: Verificar APIs del módulo en producción
        run: |
          curl -f "${{ secrets.PRODUCTION_API_URL }}/api/lab/products" || exit 1
          curl -f "${{ secrets.PRODUCTION_API_URL }}/api/lab/activities" || exit 1
          echo "✅ APIs del módulo funcionando en producción"
      
      - name: Notificar si hay problemas
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: '❌ Problemas detectados en el Módulo de Laboratorios en producción'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} 